# Tempo Configuration
# Optimized for Docker Compose deployment

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6831
        thrift_compact:
          endpoint: 0.0.0.0:6832
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  ring:
    kvstore:
      store: inmemory
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 336h  # 14 days
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
      bloom_filter_shard_size_bytes: 256
      version: vParquet
      encoding: zstd
    wal:
      path: /var/tempo/wal
      encoding: snappy
    local:
      path: /var/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095
  max_concurrent_queries: 20
  search:
    prefer_self: 10
    external_endpoints: []
  trace_by_id:
    query_timeout: 30s

query_frontend:
  max_outstanding_per_tenant: 2000
  search:
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600
  trace_by_id:
    query_shards: 50

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
    ingestion:
      max_traces_per_user: 100000
      max_global_traces_per_user: 100000
      max_bytes_per_trace: 5000000
      ingestion_rate_limit_bytes: 20000000
      ingestion_burst_size_bytes: 30000000